name: Deploy feature branches to non prd environment

on:
  push:
    branches:
      - feature*
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: cfst-3457-d7cf858686255903632b7341e-nonprodbucket-1mw5khpdml8g6
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: configure-aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secret.AWS-ACCESS-KEY-ID }}
          aws-secret-access-key: ${{ secret.AWS-SECRET-ACCESS-KEY }}
          aws-region: us-east-1
      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: build
        run: |
          npm ci 
          npm run build
      - name: deploy to s3 bucket
        run: aws s3 cp public s3://${{ env.BUCKET_NAME }}/ --recursive --acl public-read